import { Product, HeroSlide, BrandingSettings } from '../types';

export const INITIAL_BRANDING: BrandingSettings = {
  websiteName: 'Outfit',
  websiteTitle: 'Outfit | Luxury Fashion & Modern Tailoring',
  websiteDescription: 'Discover our curated capsule of architectural apparel, handcrafted modern leather goods, and refined everyday essentials designed for timeless living.',
  logoUrl: '',
  faviconUrl: '',
  logoHeight: 36,
  logoTextScale: 100,
  showLogoText: true,
  currency: '৳',
  contactEmail: 'concierge@outfit.luxury',
  contactPhone: '+880 1342-826145',
  bkashNumber: '01342826145',
  freeShippingThreshold: 0,
  deliveryFee: 150,
  fontFamily: 'Poppins',
  bodyFontFamily: 'Poppins',
  updatedAt: new Date().toISOString(),
};

export const INITIAL_HERO_SLIDES: HeroSlide[] = [
  {
    id: 'slide_1',
    index: 0,
    title: 'Autumn Monolith Collection',
    subtitle: 'Sculptural silhouettes crafted from virgin wool and organic double-faced cashmere.',
    tag: 'NEW ARRIVALS 2026',
    imageUrl: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=2070&auto=format&fit=crop',
    buttonText: 'Explore Collection',
    buttonLink: 'Apparel',
    align: 'left',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'slide_2',
    index: 1,
    title: 'Architectural Leather Goods',
    subtitle: 'Full-grain Italian calfskin engineered for the modern nomad and discerning collector.',
    tag: 'HANDCRAFTED ATELIER',
    imageUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?q=80&w=2070&auto=format&fit=crop',
    buttonText: 'Shop Accessories',
    buttonLink: 'Accessories',
    align: 'center',
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'slide_3',
    index: 2,
    title: 'Timeless Everyday Essentials',
    subtitle: 'Pure geometric forms, muted mineral tones, and unmatched daily tactile luxury.',
    tag: 'LIMITED EDITION',
    imageUrl: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=2070&auto=format&fit=crop',
    buttonText: 'Discover Footwear',
    buttonLink: 'Footwear',
    align: 'right',
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    name: 'Cashmere Double-Breasted Overcoat',
    description: 'Masterfully tailored in northern Italy with 100% Mongolian virgin cashmere. Features drop shoulders, horn buttons, dual front welt pockets, and a relaxed architectural silhouette.',
    price: 420,
    originalPrice: 580,
    discountPercentage: 28,
    stock: 14,
    category: 'Apparel',
    images: [
      'https://images.unsplash.com/photo-1539533018447-63fcce2678e3?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1200&auto=format&fit=crop',
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Oatmeal Heather', hex: '#d9cdbe' },
      { name: 'Charcoal Noir', hex: '#262626' },
      { name: 'Camel Tan', hex: '#b58a63' },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 42,
    badge: 'BESTSELLER',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_2',
    name: 'Minimalist Structured Leather Tote',
    description: 'Sculpted from vegetable-tanned Tuscan leather that develops a rich, unique patina over time. Includes an interior magnetic laptop divider and brass protective hardware.',
    price: 290,
    originalPrice: 340,
    discountPercentage: 15,
    stock: 8,
    category: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?q=80&w=1200&auto=format&fit=crop',
    ],
    sizes: ['Standard 15"', 'Mini 11"'],
    colors: [
      { name: 'Midnight Black', hex: '#1c1917' },
      { name: 'Warm Cognac', hex: '#9a3412' },
      { name: 'Forest Moss', hex: '#2d3748' },
    ],
    featured: true,
    rating: 4.8,
    reviewCount: 29,
    badge: 'NEW',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_3',
    name: 'Handcrafted Ceramic Dial Watch',
    description: 'Precision Japanese automatic movement housed in a matte ceramic case with sapphire crystal glass and a genuine calfskin strap. Water resistant to 50 meters.',
    price: 360,
    originalPrice: 450,
    discountPercentage: 20,
    stock: 6,
    category: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?q=80&w=1200&auto=format&fit=crop',
    ],
    sizes: ['38mm', '42mm'],
    colors: [
      { name: 'Matte White', hex: '#f8fafc' },
      { name: 'Obsidian Black', hex: '#0f172a' },
    ],
    featured: true,
    rating: 5.0,
    reviewCount: 18,
    badge: 'LIMITED',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_4',
    name: 'Raw Edge Merinos Knit Sweater',
    description: 'Chunky mid-weight knit woven from 100% sustainably sourced extra-fine merino wool. Designed with rolled hems and micro-ribbed crew neck for casual elegance.',
    price: 185,
    originalPrice: 220,
    discountPercentage: 16,
    stock: 22,
    category: 'Apparel',
    images: [
      'https://images.unsplash.com/photo-1576566588028-4147f3842f27?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1434389677669-e08b4cac3105?q=80&w=1200&auto=format&fit=crop',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Ecru Chalk', hex: '#f5f5f4' },
      { name: 'Sage Gray', hex: '#9ca3af' },
      { name: 'Espresso', hex: '#44403c' },
    ],
    featured: false,
    rating: 4.7,
    reviewCount: 33,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_5',
    name: 'Minimalist Monolithic Leather Loafers',
    description: 'Supple full-grain box calf leather with padded memory foam insole and lightweight EVA lug sole for extraordinary all-day cushioning.',
    price: 240,
    originalPrice: 295,
    discountPercentage: 19,
    stock: 12,
    category: 'Footwear',
    images: [
      'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?q=80&w=1200&auto=format&fit=crop',
    ],
    sizes: ['EU 40', 'EU 41', 'EU 42', 'EU 43', 'EU 44', 'EU 45'],
    colors: [
      { name: 'Polished Black', hex: '#18181b' },
      { name: 'Dark Burgundy', hex: '#450a0a' },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 51,
    badge: 'POPULAR',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_6',
    name: 'Matte Ceramic Studio Diffuser Lamp',
    description: 'Dual-purpose sculptural lighting piece and ultrasonic ambient aroma diffuser. Cast in porous unglazed stoneware with soft touch dimmer switch.',
    price: 135,
    originalPrice: 160,
    discountPercentage: 15,
    stock: 19,
    category: 'Living',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?q=80&w=1200&auto=format&fit=crop',
    ],
    sizes: ['One Size'],
    colors: [
      { name: 'Terracotta Sand', hex: '#d4a373' },
      { name: 'Ash White', hex: '#e2e8f0' },
    ],
    featured: false,
    rating: 4.6,
    reviewCount: 14,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_7',
    name: 'Silk-Tencel Relaxed Camp Collar Shirt',
    description: 'Fluid drape cut with breathable Lyocell-silk blend. Mother-of-pearl buttons and straight hem with side vents for understated warm-weather layering.',
    price: 145,
    originalPrice: 180,
    discountPercentage: 19,
    stock: 16,
    category: 'Apparel',
    images: [
      'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1620012253295-c15c429fcc71?q=80&w=1200&auto=format&fit=crop',
    ],
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Olive Drab', hex: '#556b2f' },
      { name: 'Pure Chalk', hex: '#fafafa' },
      { name: 'Muted Navy', hex: '#1e293b' },
    ],
    featured: false,
    rating: 4.8,
    reviewCount: 22,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prod_8',
    name: 'Precision Titanium Frame Sunglasses',
    description: 'Ultra-lightweight Japanese aerospace grade titanium frames with polarized UV400 anti-reflective lenses. Custom engraved bridge.',
    price: 210,
    originalPrice: 260,
    discountPercentage: 19,
    stock: 7,
    category: 'Accessories',
    images: [
      'https://images.unsplash.com/photo-1511499767150-a48a237f0083?q=80&w=1200&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?q=80&w=1200&auto=format&fit=crop',
    ],
    sizes: ['51-20-145mm'],
    colors: [
      { name: 'Satin Gold', hex: '#d4af37' },
      { name: 'Brushed Silver', hex: '#cbd5e1' },
      { name: 'Gunmetal', hex: '#334155' },
    ],
    featured: true,
    rating: 4.9,
    reviewCount: 38,
    badge: 'EXCLUSIVE',
    createdAt: new Date().toISOString(),
  },
];
